a1 = input("Enter a Fruit 1 : ")
a2 = input("Enter a Fruit 2 : ")
a3 = input("Enter a Fruit 3 : ")
a4 = input("Enter a Fruit 4 : ")
a5 = input("Enter a Fruit 5 : ")
a6 = input("Enter a Fruit 6 : ")
a7 = input("Enter a Fruit 7 : ")
fruit_list = [a1, a2, a3, a4, a5, a6, a7]
print(fruit_list)
print(type(fruit_list))
